DROP INDEX IF EXISTS email_uidx;
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL DEFAULT '',
	email VARCHAR(255) NOT NULL DEFAULT '',
	telefone VARCHAR(11) NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX email_uidx ON usuarios (email);
 